apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: custom-nginx-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
