apiVersion: v1
kind: Pod
metadata:
  name: student-pod-reader-pod
  namespace: student-space
spec:
  serviceAccountName: student-pod-reader
  containers:
    - name: reader
      image: nicolaka/netshoot:latest
      command:
        - bash
        - -lc
        - trap 'exit 0' TERM; while true; do sleep 1; done
