apiVersion: v1
kind: Pod
metadata:
  name: custom-nginx
spec:
  imagePullSecrets:
    - name: private-registry-credentials
  containers:
    - name: nginx
      image: k8s-master:8082/nginx:1.25-custom-index
      ports:
        - containerPort: 80
