apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  restartPolicy: Never
  containers:
    - name: hello-world
      image: busybox:1.36.1
      command:
        - sh
        - -c
        - echo "Hello, World! :D"
