apiVersion: v1
kind: Pod
metadata:
  name: nginx-debug
  labels:
    app: nginx-debug
  annotations:
    extrainformation: "This is some extra information we added about this pod. It can be longer than what a label stores."
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
