apiVersion: v1
kind: Pod
metadata:
  name: worker-1-nginx
  labels:
    app: worker-1-nginx
spec:
  nodeName: k8s-worker-1
  volumes:
    - name: html-volume
      hostPath:
        path: /home/vagrant/volumes-example
        type: Directory
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
          readOnly: false
