apiVersion: v1
kind: Pod
metadata:
  name: fly
spec:
  tolerations:
    - key: mosquito-spray
      operator: Exists
      effect: NoSchedule
  containers:
    - name: fly
      image: busybox:1.36.1
      command:
        - sh
        - -c
        - trap 'exit 0' TERM; while true; do sleep 1; done
